### ISSUE TITLE
I want to get imperceptible images only!

### ISSUE THREAD

**Issue by giangnguyen2412** [AllenChen1998/DAmageNet#2]
Hi Allen, thanks for your excellent work.

I would like to use your dataset in our research. However, I only want to get images having imperceptible changes to human eyes?
Do I have any method to achieve them?

Thank you.

**Comment by Sizhe-Chen** [comment]
Hi, thanks for your interest on DAmageNet. It could be downloaded from http://www.pami.sjtu.edu.cn/Show/56/122, as described in the readme.
 
From: Giang Nguyen
Date: 2020-10-06 16:52
To: AllenChen1998/DAmageNet
CC: Subscribed
Subject: [AllenChen1998/DAmageNet] I want to get imperceptible images only! (#2)
Hi Allen, thanks your for excellent work.
I would like to use your dataset in our research. However, I only want to get images having imperceptible changes to human eyes?
Do I have any method to achieve them?
Thank you.

**Comment by giangnguyen2412** [comment]
Hi Allen,

I meant only imperceptible images (images seems totally similar with the
original images). In your dataset, there are images containg artifacts and
they are not similar to the original ones.

Giang

Vào 22:00, T.3, 6 Th10, 2020 陈思哲 <notifications@github.com> đã viết:

**Comment by Sizhe-Chen** [comment]
Thanks for pointing out that. Actually, we create two versions of DAmageNet and what you mean is the 2nd one. The 1st one could also be downloaded on that webpage (link at the bottom). The 1st version has smaller l2-norm perturbations, which however, is not l-\infty bounded, leading to better transferability. The 2st version has bigger l2-norm perturbations, but is l-\infty bounded. You could see if the 1st version meets your requirements.

**Comment by giangnguyen2412** [comment]
Hi Allen,

Thanks a lot for your kind reply. Can you send me the links to both
versions.

Thank you a lot!

Vào 00:12, T.4, 7 Th10, 2020 陈思哲 <notifications@github.com> đã viết:

**Comment by giangnguyen2412** [comment]
You mean the `old `and `new `version from this [link](http://www.pami.sjtu.edu.cn/Show/56/122)? If I only want to get imperceptible images, I should go into the new version, right?
